-- MySQL Script generated by MySQL Workbench
-- Wed Jun 28 00:19:28 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema AiesecApp
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema AiesecApp
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `AiesecApp` DEFAULT CHARACTER SET utf8 ;
USE `AiesecApp` ;

-- -----------------------------------------------------
-- Table `AiesecApp`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AiesecApp`.`User` (
  `idUser` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(255) NOT NULL,
  `username` VARCHAR(100) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `shortBio` VARCHAR(255) NULL,
  `createdDate` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedDate` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `approved` TINYINT NOT NULL DEFAULT 0,
  `userType` TINYINT NOT NULL COMMENT 'Should be a value ranging from 1 to 3, admin : 1 , project : 2 , ep : 3',
  `expired` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`idUser`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AiesecApp`.`Country`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AiesecApp`.`Country` (
  `idCountry` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `countryCode` VARCHAR(45) NOT NULL,
  `description` VARCHAR(255) NULL,
  `locationCoordinates` VARCHAR(255) NULL,
  PRIMARY KEY (`idCountry`),
  UNIQUE INDEX `countryCode_UNIQUE` (`countryCode` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AiesecApp`.`Project`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AiesecApp`.`Project` (
  `idProject` INT NOT NULL AUTO_INCREMENT,
  `projectName` VARCHAR(255) NOT NULL,
  `shortDescription` VARCHAR(255) NOT NULL,
  `longDescription` VARCHAR(1500) NULL,
  `startDate` DATETIME NOT NULL,
  `endDate` DATETIME NOT NULL,
  `createdDate` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `expired` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`idProject`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AiesecApp`.`ExchangeParticipant`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AiesecApp`.`ExchangeParticipant` (
  `idExchangeParticipant` INT NOT NULL AUTO_INCREMENT,
  `User_idUser` INT NOT NULL,
  `Country_idCountry` INT NOT NULL,
  `Project_idProject` INT NOT NULL,
  PRIMARY KEY (`idExchangeParticipant`),
  INDEX `fk_ExchangeParticipant_Users_idx` (`User_idUser` ASC),
  INDEX `fk_ExchangeParticipant_Country1_idx` (`Country_idCountry` ASC),
  INDEX `fk_ExchangeParticipant_Project1_idx` (`Project_idProject` ASC),
  CONSTRAINT `fk_ExchangeParticipant_Users`
    FOREIGN KEY (`User_idUser`)
    REFERENCES `AiesecApp`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ExchangeParticipant_Country1`
    FOREIGN KEY (`Country_idCountry`)
    REFERENCES `AiesecApp`.`Country` (`idCountry`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ExchangeParticipant_Project1`
    FOREIGN KEY (`Project_idProject`)
    REFERENCES `AiesecApp`.`Project` (`idProject`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AiesecApp`.`UserRole`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AiesecApp`.`UserRole` (
  `idUserRole` INT NOT NULL AUTO_INCREMENT,
  `role` VARCHAR(100) NOT NULL,
  `roleDescription` VARCHAR(255) NULL,
  `createdDate` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedDate` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `expired` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`idUserRole`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AiesecApp`.`AdminUserRole`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AiesecApp`.`AdminUserRole` (
  `idAdminUserRole` INT NOT NULL AUTO_INCREMENT,
  `adminRole` VARCHAR(100) NOT NULL,
  `description` VARCHAR(255) NULL,
  `createdDate` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `expired` TINYINT NULL DEFAULT 0,
  PRIMARY KEY (`idAdminUserRole`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AiesecApp`.`ProjectUserRole`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AiesecApp`.`ProjectUserRole` (
  `idProjectUserRole` INT NOT NULL AUTO_INCREMENT,
  `User_idUser` INT NOT NULL,
  `UserRole_idUserRole` INT NOT NULL,
  `Project_idProject` INT NOT NULL,
  `createdDate` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedDate` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `expired` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`idProjectUserRole`, `User_idUser`, `UserRole_idUserRole`, `Project_idProject`),
  INDEX `fk_ProjectUserRole_User1_idx` (`User_idUser` ASC),
  INDEX `fk_ProjectUserRole_UserRole1_idx` (`UserRole_idUserRole` ASC),
  INDEX `fk_ProjectUserRole_Project1_idx` (`Project_idProject` ASC),
  CONSTRAINT `fk_ProjectUserRole_User1`
    FOREIGN KEY (`User_idUser`)
    REFERENCES `AiesecApp`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ProjectUserRole_UserRole1`
    FOREIGN KEY (`UserRole_idUserRole`)
    REFERENCES `AiesecApp`.`UserRole` (`idUserRole`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ProjectUserRole_Project1`
    FOREIGN KEY (`Project_idProject`)
    REFERENCES `AiesecApp`.`Project` (`idProject`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AiesecApp`.`AdminUser`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AiesecApp`.`AdminUser` (
  `User_idUser` INT NOT NULL,
  `AdminUserRole_idAdminUserRole` INT NOT NULL,
  `createdDate` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedDate` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `expired` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`User_idUser`, `AdminUserRole_idAdminUserRole`),
  INDEX `fk_AdminUser_AdminUserRole1_idx` (`AdminUserRole_idAdminUserRole` ASC),
  CONSTRAINT `fk_AdminUser_User1`
    FOREIGN KEY (`User_idUser`)
    REFERENCES `AiesecApp`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_AdminUser_AdminUserRole1`
    FOREIGN KEY (`AdminUserRole_idAdminUserRole`)
    REFERENCES `AiesecApp`.`AdminUserRole` (`idAdminUserRole`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AiesecApp`.`ProjectUpdate`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AiesecApp`.`ProjectUpdate` (
  `idProjectUpdate` INT NOT NULL AUTO_INCREMENT,
  `Project_idProject` INT NOT NULL,
  `User_idUser` INT NOT NULL,
  `description` VARCHAR(255) NOT NULL,
  `createdDate` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedDate` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `expired` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`idProjectUpdate`, `Project_idProject`, `User_idUser`),
  INDEX `fk_ProjectUpdate_User1_idx` (`User_idUser` ASC),
  CONSTRAINT `fk_ProjectUpdate_Project1`
    FOREIGN KEY (`Project_idProject`)
    REFERENCES `AiesecApp`.`Project` (`idProject`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ProjectUpdate_User1`
    FOREIGN KEY (`User_idUser`)
    REFERENCES `AiesecApp`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AiesecApp`.`Complain`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AiesecApp`.`Complain` (
  `idComplain` INT NOT NULL AUTO_INCREMENT,
  `ExchangeParticipant_idExchangeParticipant` INT NOT NULL,
  `Project_idProject` INT NOT NULL,
  `description` VARCHAR(255) NOT NULL,
  `createdDate` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedDate` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `complainStatus` TINYINT NULL DEFAULT 0 COMMENT 'if complain resolved complainStatus : 1 default value is 0',
  PRIMARY KEY (`idComplain`),
  INDEX `fk_Complain_ExchangeParticipant1_idx` (`ExchangeParticipant_idExchangeParticipant` ASC),
  INDEX `fk_Complain_Project1_idx` (`Project_idProject` ASC),
  CONSTRAINT `fk_Complain_ExchangeParticipant1`
    FOREIGN KEY (`ExchangeParticipant_idExchangeParticipant`)
    REFERENCES `AiesecApp`.`ExchangeParticipant` (`idExchangeParticipant`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Complain_Project1`
    FOREIGN KEY (`Project_idProject`)
    REFERENCES `AiesecApp`.`Project` (`idProject`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AiesecApp`.`ComplainReply`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AiesecApp`.`ComplainReply` (
  `idComplainReply` INT NOT NULL,
  `Complain_idComplain` INT NOT NULL,
  `User_idUser` INT NOT NULL,
  `replyText` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idComplainReply`),
  INDEX `fk_ComplainReply_Complain1_idx` (`Complain_idComplain` ASC),
  INDEX `fk_ComplainReply_User1_idx` (`User_idUser` ASC),
  CONSTRAINT `fk_ComplainReply_Complain1`
    FOREIGN KEY (`Complain_idComplain`)
    REFERENCES `AiesecApp`.`Complain` (`idComplain`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ComplainReply_User1`
    FOREIGN KEY (`User_idUser`)
    REFERENCES `AiesecApp`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AiesecApp`.`ProjectEvent`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AiesecApp`.`ProjectEvent` (
  `idProjectEvent` INT NOT NULL AUTO_INCREMENT,
  `Project_idProject` INT NOT NULL,
  `User_idUser` INT NOT NULL,
  `createdDate` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedDate` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `venue` VARCHAR(255) NOT NULL,
  `start` DATETIME NOT NULL,
  `end` DATETIME NOT NULL,
  `description` VARCHAR(255) NOT NULL,
  `expired` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`idProjectEvent`),
  INDEX `fk_ProjectEvent_Project1_idx` (`Project_idProject` ASC),
  INDEX `fk_ProjectEvent_User1_idx` (`User_idUser` ASC),
  CONSTRAINT `fk_ProjectEvent_Project1`
    FOREIGN KEY (`Project_idProject`)
    REFERENCES `AiesecApp`.`Project` (`idProject`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ProjectEvent_User1`
    FOREIGN KEY (`User_idUser`)
    REFERENCES `AiesecApp`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AiesecApp`.`SurveyResponse`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AiesecApp`.`SurveyResponse` (
  `idSurveyResponse` INT NOT NULL AUTO_INCREMENT,
  `ExchangeParticipant_idExchangeParticipant` INT NOT NULL,
  `Project_idProject` INT NOT NULL,
  `createdDate` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`idSurveyResponse`, `ExchangeParticipant_idExchangeParticipant`, `Project_idProject`),
  INDEX `fk_SurveyResponse_ExchangeParticipant1_idx` (`ExchangeParticipant_idExchangeParticipant` ASC),
  INDEX `fk_SurveyResponse_Project1_idx` (`Project_idProject` ASC),
  CONSTRAINT `fk_SurveyResponse_ExchangeParticipant1`
    FOREIGN KEY (`ExchangeParticipant_idExchangeParticipant`)
    REFERENCES `AiesecApp`.`ExchangeParticipant` (`idExchangeParticipant`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_SurveyResponse_Project1`
    FOREIGN KEY (`Project_idProject`)
    REFERENCES `AiesecApp`.`Project` (`idProject`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AiesecApp`.`ResponseDetail`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AiesecApp`.`ResponseDetail` (
  `idResponseDetail` INT NOT NULL AUTO_INCREMENT,
  `SurveyResponse_idSurveyResponse` INT NOT NULL,
  `createdDate` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`idResponseDetail`, `SurveyResponse_idSurveyResponse`),
  INDEX `fk_ResponseDetail_SurveyResponse1_idx` (`SurveyResponse_idSurveyResponse` ASC),
  CONSTRAINT `fk_ResponseDetail_SurveyResponse1`
    FOREIGN KEY (`SurveyResponse_idSurveyResponse`)
    REFERENCES `AiesecApp`.`SurveyResponse` (`idSurveyResponse`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AiesecApp`.`UserPersonalInfo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AiesecApp`.`UserPersonalInfo` (
  `idUserPersonalInfo` INT NOT NULL AUTO_INCREMENT,
  `User_idUser` INT NOT NULL,
  `firstName` VARCHAR(255) NOT NULL,
  `lastName` VARCHAR(255) NOT NULL,
  `currentResidence` VARCHAR(255) NOT NULL,
  `mobileNumber` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idUserPersonalInfo`),
  INDEX `fk_UserPersonalInfo_User1_idx` (`User_idUser` ASC),
  CONSTRAINT `fk_UserPersonalInfo_User1`
    FOREIGN KEY (`User_idUser`)
    REFERENCES `AiesecApp`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
